1. Scrivere una funzione ricorsiva che calcola la somma dei primi n numeri

In [ ]:
def sumOfNumbers(n):
    if n < 0 or not isinstance(n, int):
        return None
    elif n == 0:
        return n
    else:
        return n + sumOfNumbers(n-1)
    
print (sumOfNumbers(1000))

2. Scrivere una funzione ricorsiva che calcola la potenza di un numero

In [ ]:
def power(b, e):
    if e < 0 or not isinstance(e, int):
        return None
    elif e == 0:
        return 1
    elif e == 1:
        return b
    else:
        return b * power(b, e-1)
    
print (power(2, 5))

3. Il Triangolo di Pascal è un insieme di numeri organizzati in un triangolo di numeri tali che

$$a_{nr}=\frac{n!}{r!(n−r)!}$$

Questa equazione è l'equazione del coefficiente binomiale. Possiamo costruire il triangolo di Pascal sommando i due numeri che sono sopra (diagonalmente) a ciascun numero. Per esempio:
```

        1
      1   1
    1   2   1
  1   3   3   1
1   4   6   4   1
```
Scrivere un programma che stampa il triangolo di Pascal. Il programma deve accettare un parametro che dice il numero di righe da stampare. 

$$
\begin{matrix}
1 & 0 & 0 & 0 & 0\\
1 & 1 & 0 & 0 & 0\\
1 & 2 & 1 & 0 & 0\\
1 & 3 & 3 & 1 & 0\\
1 & 4 & 6 & 4 & 1
\end{matrix}
$$

$$
a_i = \begin{cases}
    1 & i = 0, i = n\\
    0 &i < n\\
    a_{i - n} + a_{i - n - 1} &i > n\\
    \end{cases}
$$

In [20]:
def pascal(n):
    m = [0] * n**2
    for i in range(n**2):
        if i == 0 or i == n:
            m[i] = 1
        elif i < n:
            m[i] = 0
        else:
            m[i] = m[i-n] + m[i-n-1]b
    return m

In [24]:
import numpy as np
print(np.array(pascal(10)).reshape(10,10))

[[  1   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0]
 [  1   2   1   0   0   0   0   0   0   0]
 [  1   3   3   1   0   0   0   0   0   0]
 [  1   4   6   4   1   0   0   0   0   0]
 [  1   5  10  10   5   1   0   0   0   0]
 [  1   6  15  20  15   6   1   0   0   0]
 [  1   7  21  35  35  21   7   1   0   0]
 [  1   8  28  56  70  56  28   8   1   0]
 [  1   9  36  84 126 126  84  36   9   1]]


In [6]:
def pascal(n,k):
    if k == 0 or k == n:
        return 1
    else:
        return (pascal(n-1, k-1) + pascal(n-1, k))

In [27]:
for n in range (7):
    for k in range (n+1):
        print (pascal(n, k), ' ', end='')
    print()

1  
1  1  
1  2  1  
1  3  3  1  
1  4  6  4  1  
1  5  10  10  5  1  
1  6  15  20  15  6  1  


4. I numeri di Catalan sono una sequenza di interi particolare. Realizzare una funzione ricorsiva, che dato un numero n calcola (e restituisce) l'n-esimo numero delle sequenza in base alla definizione induttiva fornita di seguito
$$
C_0 = 1\\
C_{n+1} = \frac{4n+2}{n+2}C_n
$$

In [ ]:
def catalan(n):
    if n == 0:
        return 1
    else:
        return int((4 * n - 2)/(n + 1) * catalan(n-1))

for i in range(10):
    print (catalan(i))

5. Verifica (ricorsiva) di proprietà. Scrivere una funzione ricorsiva che legge da input una sequenza di valori interi positivi terminata dal valore 0 (che non fa parte della sequenza) e che verifica la seguente proprietà: ogni valore letto è doppio del valore precedente. Ad esempio la sequenza 2 4 8 16 32 0 verifica la proprietà. La funzione deve restituire 1 se la proprietà è verificata e 0 altrimenti e non può utilizzare gli array.

In [20]:
def checkDouble(prev = 0):
    n = int(input("Numero: "))
    if prev == 0:
        return checkDouble(n)
    if n == 0:
        return True
    if n != prev*2:
        return False
    else:
        return checkDouble(n)

6. Inversione di una stringa ricorsiva. Scrivere un programma che legge una sequenza di interi terminata da 0 (chiede un intero alla volta) e stampa la sequenze invertita sullo schermo. Ad esempio, leggendo la sequenza 1 8 3 4 6 0, deve stampare 6 4 3 8 1. Il programma deve fare uso di una funzione ricorsiva e non può usare liste o array.

In [6]:
def reverse(n = 0):
    n = int(input("Dammi un numero: "))
    if n != 0:
        reverse(n)
        print(n)

7. Implementare una funzione ricorsiva hanoi(n,A,C,B) che stampa tutti gli spostamenti necessari per risolvere la Torre di Hanoi con n dischi. Sviluppare un programma che chiede all’utente di inserire n da standard input e stampa le mosse necessarie sullo standard output.

In [3]:
def hanoi(n, A="A", B="B", C="C"):
    if n == 1:
        print (f"{A} -> {B}")
    else:
        hanoi(n-1, A, C, B)
        print (f"{A} -> {B}")
        hanoi(n-1, C, B, A)
n = int(input("Quanti dischi? "))
hanoi(n)

Quanti dischi? 10
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
A -> B
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
B -> A
C -> B
C -> A
B -> A
B -> C
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
A -> B
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
C -> A
B -> A
B -> C
A -> C
B -> A
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
A -> B
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
B -> A
C -> B
C -> A
B -> A
B -> C
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
B -> A
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
C -> A
B -> A
B -> C
A -> C
B -> A
C -> B
C -> A
B -> A
B -> C
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
A -> B
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
B -> A
C -> B
C -> A
B -> A
B -> C
A -> C
A -> B
C -> B
A -> C
B -> A
B -> C
A -> C
A -> B
C -> B
C -> A
B -> A
C -> B
A -> C
A -> B
C -> B
C -> A
B -> A
B -> C
A -> C
B -> A
C 